### ISSUE TITLE
执行npm install的时候报下面的错误

### ISSUE THREAD

**Issue by light-dot** [archguard/archguard-frontend#24]
```
29141 verbose stack Error: sha512-ki1/VuRIHFCzxWNrsshHYPs6L7TvLu3DL+TyIGEsRcvVERmxokbf5Gdk7mFxZnTdiGtnA4cfSmjZJMviqSuZrQ== integrity checksum failed when using sha512: wanted sha512-ki1/VuRIHFCzxWNrsshHYPs6L7TvLu3DL+TyIGEsRcvVERmxokbf5Gdk7mFxZnTdiGtnA4cfSmjZJMviqSuZrQ== but got sha512-rUKh17LeUYNeZrUQWdcuQR65T9Mw8E9TGsvX3qpM/8FlmBWYxZTBbvSrnu/tnS20Ct643G3wWZbwmsh8Of2fWQ==. (5701632 bytes)
29141 verbose stack     at Transform.on (C:\qianduan\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
29141 verbose stack     at emitNone (events.js:111:20)
29141 verbose stack     at Transform.emit (events.js:208:7)
29141 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
29141 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
29141 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
29142 verbose cwd D:\work\common\github\archguard-frontend\archguard
29143 verbose Windows_NT 10.0.22621
29144 verbose argv "C:\\qianduan\\nodejs\\node.exe" "C:\\qianduan\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
29145 verbose node v8.11.3
29146 verbose npm  v5.6.0
29147 error code EINTEGRITY
29148 error sha512-ki1/VuRIHFCzxWNrsshHYPs6L7TvLu3DL+TyIGEsRcvVERmxokbf5Gdk7mFxZnTdiGtnA4cfSmjZJMviqSuZrQ== integrity checksum failed when using sha512: wanted sha512-ki1/VuRIHFCzxWNrsshHYPs6L7TvLu3DL+TyIGEsRcvVERmxokbf5Gdk7mFxZnTdiGtnA4cfSmjZJMviqSuZrQ== but got sha512-rUKh17LeUYNeZrUQWdcuQR65T9Mw8E9TGsvX3qpM/8FlmBWYxZTBbvSrnu/tnS20Ct643G3wWZbwmsh8Of2fWQ==. (5701632 bytes)
29149 verbose exit [ 1, true ]
```

**Comment by phodal** [comment]
上面的日志写得很清楚……你的网络问题
